server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/formation
    username: postgres
    password: test123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
logging:
  level: info




